### ISSUE TITLE
Setting up the login

### ISSUE THREAD

**Issue by taldarim3** [IgorKordiukiewicz/TaskTracker#1]
Hi, I really liked your project and I would like to run it locally. But I've never worked with Auth0. Could you tell me how to set it up correctly?
I set my Domain and ClientID in the application configuration, but I still get an error like in the screenshot when logging in.
![image](https://github.com/IgorKordiukiewicz/TaskTracker/assets/79811653/db1bee35-e14b-4406-8e7c-812b87bcc344)

Also, could you show the callbacks that you use in Auth0?

**Comment by IgorKordiukiewicz** [comment]
Hi, here is a tutorial from Auth0 on how to setup auth for Blazor WASM: [https://auth0.com/blog/securing-blazor-webassembly-apps/](https://auth0.com/blog/securing-blazor-webassembly-apps/). 
And these are the settings for your SPA in Auth0:
![image](https://github.com/IgorKordiukiewicz/TaskTracker/assets/25117425/af0dc583-9a7f-4716-8a05-00688d8cfc0b)
